#!/usr/bin/env python3
"""Write ``davideo/_build.py`` so the about box can say when this was built.

Run it in the source tree right before building a package:

    python scripts/stamp_build.py          # git HEAD's time + sha, else now
    python scripts/stamp_build.py --now    # always "now", ignore git

The generated file is optional and never committed: without it davideo reads
git HEAD at runtime (works from a checkout), and without that too the about box
just says "unknown". It exists for the case where neither is available -- an
installed package, whose .git was left behind in the build tree. That's the
AUR ``-git`` package: build in the checkout, stamp, then install.

SOURCE_DATE_EPOCH wins over everything when set, so reproducible builds stay
reproducible.
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from davideo.core.buildinfo import git_head

TARGET = Path(__file__).resolve().parent.parent / "davideo" / "_build.py"


def main(argv: list[str]) -> int:
    epoch = os.environ.get("SOURCE_DATE_EPOCH", "").strip()
    iso, commit = ("", "") if "--now" in argv else git_head()
    if epoch:
        when, source = (
            datetime.fromtimestamp(int(epoch), timezone.utc).isoformat(),
            "SOURCE_DATE_EPOCH",
        )
    elif iso:
        when, source = iso, "git HEAD"
    else:
        when, source = datetime.now().astimezone().isoformat(), "build time"

    TARGET.write_text(
        '"""Generated by scripts/stamp_build.py. Not committed; safe to delete."""\n'
        f"\nBUILD_TIME = {when!r}\nCOMMIT = {commit!r}\n",
        encoding="utf-8",
    )
    print(f"{TARGET}: {when} ({source})" + (f", commit {commit}" if commit else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
